### ISSUE TITLE
Weak feedback when no results return

### ISSUE THREAD

**Issue by alemela** [nexacenter/public-contracts#10]
It's not so clear the difference between a request with zero results, a wrong request or a server failure because there is quite no feedback.

**Comment by nicorusti** [comment]
Clarity can be improved when some stats about datasets will b implemented in the visualization (I.e. show an error message: 
* this PA hasn't published valid xml dataset  Please complain with the PA by writing a PEC to (and get the PEC with a sparql query on spcdata endpoint). 
* this PA hasn't communicated to ANAC the correct xml dataset url. An attempt to access the following wrong url was done on xxxxx without result.  Please complain with the PA by writing a PEC to (and get the PEC with a sparql query on spcdata endpoint).

**Comment by alemela** [comment]
I think there is a finite number of cases:
* user insert an invalid id like `antani`
* user insert a valid id but we haven't any data
    * PA hasn't published valid xml dataset 
    * PA hasn't communicated to ANAC the correct xml dataset url
    * we can't associate this id to anything
* user insert a valid id, we some data, but nothing useful to visualize
* user insert a valid id, we have data, but something goes wrong
If I haven't forgotten nothing maybe we could implement this workflow to catch all the cases and show an appropiate message (with query sparql when neccessary as Nicola said).

**Comment by alemela** [comment]
This issue was moved to synapta/public-contracts#3
