### ISSUE TITLE
Improove bubble chart 

### ISSUE THREAD

**Issue by nicorusti** [nexacenter/public-contracts#18]
If possible, i would add to the bubble chart (when mouse is passed on a bubble), some additional information about the contract (i.e. name /vatId  of the awarded tender), then i would make the bubble clickable so that you can go to see the contract on the rdf.

**Comment by alemela** [comment]
Good idea!
I think it could be enough tha name of the awarded tender on the hover panel, not to put too much info (you can always see details in the contract). To do this we have to change query sparql, matcher and template. Instead to add the clickable bubble maybe just the template.

**Comment by alemela** [comment]
This issue was moved to synapta/public-contracts#7
