### ISSUE TITLE
Business entities with C.F. show incomplete information

### ISSUE THREAD

**Issue by nicorusti** [nexacenter/public-contracts#19]
By searching BVLLSN72T50E435Z only histograms are shown, but there is no trace of the participated/won contracts. The rdf seem to have this information, instead.

**Comment by nicorusti** [comment]
The problem should be in the query sparql or in the rdf: 
The uri of this business entity is lowercase, while the VatId is uppercase. 

In both proposingStructures.json and in the contracts json where this company appears (contracts of 90021230694) the vatId is uppercase. Hence there is some problem with lowercase uri and uppercase vatId in query which generates visualization. 
Also the name of the businessEntity is not shown.

**Comment by alemela** [comment]
We have to uppercase each ids:
http://public-contracts.nexacenter.org/pc/businessEntities/bvllsn72t50e435z/html
http://public-contracts.nexacenter.org/view/BVLLSN72T50E435Z

**Comment by alemela** [comment]
Resolved in the last extraction.
