### ISSUE TITLE
Other datasets to be  added to projecs

### ISSUE THREAD

**Issue by nicorusti** [nexacenter/public-contracts#20]
Fro Traversaro; 
The ANAC Casellario delle Imprese (http://casellario.avcp.it) is a database of ~70K companies that are registered for partecipate in several kind of tenders. The data is not free, but in the past I wrote a scraper (https://classic.scraperwiki.com/scrapers/casellario_imprese_avcp/) that currently is inactive because Classic ScraperWiki is no longer working but can be reactivated if it can be useful.

The "Casellario società di ingegneria e professionali" ( http://socing.avcp.it/ ) is a register of the companies of engineering professional services. The data is not open and not easy to scrape in bulk, but an easy url can be accessed given the fiscal number of the company (see for example: http://socing.avcp.it/anagrafica.php?CodiceFiscale=06393070484 ). Hence it would be easy to get all the data related to a list of fiscal number, as the one that can be extracted from public-contracts.

**Comment by alemela** [comment]
This issue was moved to synapta/public-contracts#8
