### ISSUE TITLE
More explainations regarding payed amounts

### ISSUE THREAD

**Issue by nelsonmau** [nexacenter/public-contracts#26]
While you've found any tenders and contracts, you haven't info enough regarding **payed amounts** but just the sum. It would be great to have more details and to keep more clear source and date of payments

**Comment by Tonyz1** [comment]
are there any soldipubblici.gov.it l. open data that you can link to the payed amounts?

**Comment by alemela** [comment]
This issue was moved to synapta/public-contracts#11
