### ISSUE TITLE
Incongruences and errors in data

### ISSUE THREAD

**Issue by Lorenzocnv** [nexacenter/public-contracts#4]
Try the query below and also find the "NOCIG******" with the second/third query

--------- 1----------
```
PREFIX gr:<http://purl.org/goodrelations/v1#>
PREFIX pc: <http://purl.org/procurement/public-contracts#>
PREFIX payment: <http://reference.data.gov.uk/def/payment#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT *
WHERE {
    ?contract dcterms:identifier  ?CIG.
} ORDER BY ?contract

LIMIT 200
```
--------- 2 ---------
```
PREFIX gr:<http://purl.org/goodrelations/v1#>
PREFIX pc: <http://purl.org/procurement/public-contracts#>
PREFIX payment: <http://reference.data.gov.uk/def/payment#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT *
WHERE {
    ?contract dcterms:identifier  ?CIG.
    FILTER regex(?CIG, "^NOCIG0000") 
} ORDER BY ?contract


LIMIT 200
```
------- 3 --------
```
PREFIX gr:<http://purl.org/goodrelations/v1#>
PREFIX pc: <http://purl.org/procurement/public-contracts#>
PREFIX payment: <http://reference.data.gov.uk/def/payment#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT *
WHERE {
    ?contract dcterms:identifier  ?CIG.
    FILTER regex(?CIG, "^NOCIG00") 
} ORDER BY DESC (?contract)

LIMIT 200
```

**Comment by federicomorando** [comment]
Need to modify the following lines in xmlToJson.py in the ANAC converter:

def cigCheck (cig):
    return (cig.isalnum() and len(cig)==10 and cig!="0000000000")

We may create a new list of bad CIGs starting from your queries...

**Comment by federicomorando** [comment]
http://stackoverflow.com/questions/11251709/check-if-item-is-in-array-python

**Comment by nicorusti** [comment]
What is a list of bad cig needed for? Contracts with bad cig should already have an hash in the json contracts files. 
P.S: By law, cig may be absent in some cases

**Comment by federicomorando** [comment]
@nicorusti bad cig SHOULD already have been treated so that the ID is an hash, but there are more bad cig than the simple "0000000000"...

@Lorenzocnv there are some formatting issues in your queries: use <> for IRIs or segments of them...

PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX pc: <http://purl.org/procurement/public-contracts#>
PREFIX payment: <http://reference.data.gov.uk/def/payment#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT *
WHERE {
?contract dcterms:identifier ?CIG.
FILTER regex(?CIG, "^NOCIG0000") 
} ORDER BY ?contract

LIMIT 200

**Comment by giuseppefutia** [comment]
@nicorusti, sometimes "NOCIG" values have the correct number of characters (and you probably check it), but they are used to identify contracts without official CIGs.

See this example: http://public-contracts.nexacenter.org/pc/public_contracts/NOCIG00000/html.

We should apply an hash value as CIG id also in that cases.

**Comment by federicomorando** [comment]
a better query to have candidates for a list of bad CIGs:

PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX pc: <http://purl.org/procurement/public-contracts#>
PREFIX payment: <http://reference.data.gov.uk/def/payment#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT ?contract (COUNT(?source) AS ?count)
WHERE {
?contract dcterms:identifier ?CIG.
?contract dcterms:source ?source.
}
GROUP BY ?contract
ORDER BY DESC(?count)

LIMIT 100

**Comment by giuseppefutia** [comment]
```
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX pc: <http://purl.org/procurement/public-contracts#>
PREFIX payment: <http://reference.data.gov.uk/def/payment#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT ?contract (COUNT(?auth) AS ?count)
WHERE {
?contract dcterms:identifier ?CIG.
?contract pc:contractingAutority ?auth.
}
GROUP BY ?contract
ORDER BY DESC(?count)
OFFSET 1000
```

**Comment by Lorenzocnv** [comment]
```
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX pc: <http://purl.org/procurement/public-contracts#>
PREFIX payment: <http://reference.data.gov.uk/def/payment#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?contract (COUNT(?auth) AS ?count)
{
SELECT DISTINCT ?contract ?auth
WHERE {
?contract dcterms:identifier ?CIG.
?contract pc:contractingAutority ?auth.
}

}
GROUP BY ?contract HAVING (count(*)>1)
ORDER BY DESC(?count)
```

**Comment by alemela** [comment]
Tutti gli anni in ordine di occorrenza
```
PREFIX pc: <http://purl.org/procurement/public-contracts#>
PREFIX payment: <http://reference.data.gov.uk/def/payment#>
PREFIX time: <http://www.w3.org/2006/time#>

SELECT distinct ?year (count(?year) as ?a)

WHERE {

?c a pc:Contract .
?c time:year ?year .

}
ORDER BY DESC (?a)
```

**Comment by alemela** [comment]
Within the development of https://github.com/nexacenter/ext-public-contracts this issue become obsolete
