### ISSUE TITLE
Issues related to the visualization module

### ISSUE THREAD

**Issue by giuseppefutia** [nexacenter/public-contracts#5]
Issues related to the visualization module are related to: https://github.com/giuseppefutia/vis-public-contracts/issues

**Comment by alemela** [comment]
May I move all the vis' issues here?

**Comment by giuseppefutia** [comment]
I would say yes. For sanity we should collect all issues in one place.

**Comment by alemela** [comment]
It remains just https://github.com/giuseppefutia/vis-public-contracts/issues/15 and I'd keep there because of history.
