### ISSUE TITLE
Correct the labels searching

### ISSUE THREAD

**Issue by giuseppefutia** [nexacenter/public-contracts#6]
We must correct the mechanism for searching business entities using labels.

See these samples of business entity object:

```
{ vatID: 930bf87c8764b75984260ca8f7a322e0187088f5, name: EPUBLIC SRL }

{ vatID: 01902060035, name: EPUBLIC SRL }
```

In the search text, you are able to see both labels.

But when you choose one of them, you always obtain data related to the first business entity, that in this specific case has a bad vatID, so it is not the real "EPUBLIC SRL".

**Comment by alemela** [comment]
I see two ways.
* Add the vatID as a discriminant, so it has to be visibile right to the name in the search scrollbox. Something like "EPUBLIC SRL - 01902060035" and "EPUBLIC SRL - 930bf87c8764b75984260ca8f7a322e0187088f5". In this way you can really choose.
* Using always unique names. In this way we don't need to change the current software but we must enable a disambiguation system.
Because the vatID is IMHO the best disambiguation for our entities I'd prefere the first way.

**Comment by giuseppefutia** [comment]
I agree with you @alemela. 

The first option is also more transparent. 

We should modify the mechanism for matching the correct entity: it should check the key and the value of each business entity of each object.

**Comment by alemela** [comment]
I've done the improvement over the search box. Now it shows both label and vatId.
@giuseppefutia I haven't really understood your last sentence, what do you mean?

**Comment by giuseppefutia** [comment]
Try to type "epublic": If you choose any "EPUBLIC SRL", you always obtain the same result.

**Comment by alemela** [comment]
Ok thanks, now it's clear! I'll do it!

**Comment by alemela** [comment]
@giuseppefutia Try now :-)

**Comment by giuseppefutia** [comment]
#edaidaidai. We should explain with just one sentence how the hash values are generated. @nicorusti could you prepare it for our website?

**Comment by nicorusti** [comment]
From my code wiki: 
+ Per ciascuna gara con CIG non valido o nullo (casi di gare per le quali non è prevista l'assegnazione del cig): campo **"cigHash"**  in forma di stringa esadecimale [sha1](http://en.wikipedia.org/wiki/SHA-1), costruito in base a: 
	* Codice Fiscale della struttura proponente
	* Importo Aggiudicazione
	* Scelta Contraente (tipo di procedura di aggiudicazione) 
	* Codice Fiscale(di seguito C.F.)/p.iva dell'aggiudicatario. Nel caso l'aggiudicatario sia un raggruppamento, è utilizzato l'hash del raggruppamento, basato sui c.f/p.iva dei partecipanti in ordine alfabetico.

**Comment by giuseppefutia** [comment]
Pefect! And for business entities?

**Comment by nicorusti** [comment]
Just an hash of the name, there's no other way!

**Comment by alemela** [comment]
Probably the best is to write down those informations in the FAQ zone.

**Comment by giuseppefutia** [comment]
I agree with you, Alessio! I would also write a note in the home page, because hash values could be unclear for users. Or we write it down just in FAQs?

**Comment by alemela** [comment]
I think the hash is one of those oddities that you expect to find only sometimes. In the home page probably we have to explain only general behaviours. So, for now, I think may suffice the FAQ, but if you think the appears often no problem to add a link only in the homepage.

Probably in a short time, after other changes, we should re-think all the texts in homepage, maybe using better disposition compared to existing paragraphs.

**Comment by giuseppefutia** [comment]
Ok, for now I've updated the FAQ.
