### ISSUE TITLE
Returning unique url of the research one

### ISSUE THREAD

**Issue by nelsonmau** [nexacenter/public-contracts#7]
While I'm searching for an ID Code of Company it would be great to have an unique url of the reasearch one

**Comment by alemela** [comment]
Indeed! https://github.com/giuseppefutia/vis-public-contracts/issues/10

**Comment by alemela** [comment]
Done: http://public-contracts.nexacenter.org/view/ + vatID. 
For example: http://public-contracts.nexacenter.org/view/00518460019

**Comment by nicorusti** [comment]
What about making the business entity name linked to the uri of the business entity in the rdf? So that by clicking on name you can navigate the RDF

**Comment by alemela** [comment]
You read my mind, I'm just doing it! ;) Also putting the link "view" in the vatID label right to the name.

**Comment by alemela** [comment]
Done!
