### ISSUE TITLE
upload the whole ontology and/or make sure to declare the class of entities

### ISSUE THREAD

**Issue by federicomorando** [nexacenter/public-contracts#8]
I may be wrong, but I have the impression that the ontology that we're using is not uploaded entirely on the triple store... e.g., we miss all the GoodRelations classes.
Moreover, I assume we did not declare the fact that some entities are in a given class, although that can be inferred from the URI (which is just human cheating ;-)).

E.g., with
```
select distinct ?Concept where {[] a ?Concept} LIMIT 100
```
these are the only classes we find, apart from standard virtuoso stuff:
```
http://purl.org/goodrelations/v1#BusinessEntity
http://purl.org/procurement/public-contracts#Contract
http://purl.org/procurement/public-contracts#Tender
http://reference.data.gov.uk/def/payment#Payment
http://xmlns.com/foaf/0.1/Group
```

**Comment by alemela** [comment]
This issue was moved to synapta/public-contracts#1
